# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=228)),
            ],
        ),
        migrations.CreateModel(
            name='URLIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=228)),
            ],
        ),
        migrations.AddField(
            model_name='urlindex',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Word'),
        ),
        migrations.AddField(
            model_name='urlindex',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.URL'),
        ),
    ]
