# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=228)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
