# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_wikiresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=228, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=228, unique=True),
        ),
    ]
